import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import {MuiProvider} from "@/app/(ui)/providers/mui-provider";
import AppSidebar from "@/app/(ui)/components/sidebar/app-sidebar";
import {SidebarProvider} from "@/app/(ui)/providers/sidebar-provider";
import {ThemeSwitcherLib} from "@/app/(ui)/component-library/molecules/theme-switcher/theme-switcher-lib";
import {LegislatureProvider} from "@/app/(ui)/providers/legislature-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-scroll`}
        >
            <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem={false}
                themes={['light', 'dark', 'accessible']}
            >
                <MuiProvider>
                    <SidebarProvider>
                        <LegislatureProvider>
                        <div className="flex min-h-screen">
                            <AppSidebar />
                            <main className="flex-1 pt-14 lg:pt-0">
                                {children}
                            </main>
                            <ThemeSwitcherLib/>
                        </div>
                        </LegislatureProvider>
                    </SidebarProvider>
                </MuiProvider>
            </ThemeProvider>
        </body>
        </html>
    );
}
